import './globals.css'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  viewport: {
    width: 'device-width',
    initialScale: 1,
  },
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/*
        <head /> will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      <head />
      <body>
      <nav>
        <h1>
          My nav bar
        </h1>
      </nav>
        {children}</body>
    </html>
  )
}
